travis:
  secure:
    BINSTAR_TOKEN: Qh5/zP94iAEzflIBZE8UySEbMVAY9367d6AqjfVHhwE/OXQWXlC3/hsSWHFbocPz+Ncuw9AYBRM+t5zcziXY6sxUX3mWwDgdujfRcBMDGUaXRkGERqk8mCj4JMssko1G3kXvTmiXqXmW5uxFuloSwSF046b52+uqoIMQAuJaYjR3VUwDxNk0We8aHsVJ7AIVQdpNVdlJE+WZ4m9l25s82wCwNveT1fPi79RqL+vPHhS+rK2+oH++UEsYVR2l3D+cnrfO5/gMvLJlSe3S9PRxj8sHhBNiqpaLjW5veXpB0Pzni8no/x/+b+Zj84vd8bI4SloN/cZW2FeCiuhHeLnaX4xWNPbJXJ3fk7Hk1vIs+vIvOpcsgoempz/I5vwkPE71ElPbV1gXupeCJDHB7XrvTLVeUPnyUcm3EH1yYWS75MpjXOiMMNrJlPG9OgnlFr33mQ7OF506iHaKlBfOmkwrgguPAsAnX04XqSMsUlcmgSttXRN/GdwSN4Hc2k2lh69MeZPwZP1uKd49QqyJ/5N0vSdSNMaujFdqgNoM2vKGLupTULvstw2VxF65CzzWzsrn3QTkdbczWfS3nU1o/Tw90tlmNdSCr4uqNG7ODOr7pWMDokaAS+M142TWGVg8hAhN5it7/KABbNc/iwHkd379VBbzU57tdRWH3+roYOkJJ8s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
